### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by Snirdude** [afonsocraposo/bitalino#1]
Hey,

I'm using this plugin, however it is not null safe. I actually already cloned this repo and migrated the project using the dart migration tool. I opened a branch called null-safety-migration. I can do a pull request. I only need permissions.

**Comment by afonsocraposo** [comment]
Hello @Snirdude , thank you for your contribution. Please make a PR and I'll merge it. I can also update it in `pub.dev`.

**Comment by Snirdude** [comment]
Hi @afonsocraposo, I don't think I can make a PR without write access. Am I supposed to fork?

**Comment by afonsocraposo** [comment]
Yes, you should fork the project. Then, follow these instructions:
[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by Snirdude** [comment]
Ok no problem.

**Comment by afonsocraposo** [comment]
Thank you for your contribution!
I also updated the [pub.dev](https://pub.dev/packages/bitalino) version into [`2.0.0`](https://github.com/afonsocraposo/bitalino/commit/bcaecf245fbae8abb7bcac69ad4a0c78449dda92)
