### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by Snirdude** [afonsocraposo/bitalino#4]
I'm running my application using this plugin and I get this error. it's in the android java files. I'm not that familiar with android so please is there a chance to fix this? This happens on Android 12 Samsung S20 Ultra.

my stack trace is:
`E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): Failed to handle method call
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): java.lang.IllegalArgumentException: com.sclera.sclerapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at info.plux.pluxapi.bitalino.bth.BTHCommunication.setAlarm(BTHCommunication.java:881)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at info.plux.pluxapi.bitalino.bth.BTHCommunication.start(BTHCommunication.java:174)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at com.afonsoraposo.bitalino.BITalino.onMethodCall(BITalino.java:246)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MethodChannel#com.afonsoraposo.bitalino/bitalino( 2387): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

**Comment by afonsocraposo** [comment]
Thank you for bringing this up. Are you still experiencing this problem?

**Comment by Snirdude** [comment]
Yes, still the same problem. When I use the bitalino it crashes my app. I'm assuming it's because of this error.

**Comment by afonsocraposo** [comment]
I'm no longer working on this package. I'm currently working on a device similar to BITalino. You can learn more about it here:
https://www.instagram.com/scientissthub/

**Comment by Snirdude** [comment]
Hey @afonsocraposo,
I have an open PR for this problem. Could you review it and if it's merged then update the package in pub.dev?
Thank you :)

**Comment by afonsocraposo** [comment]
Thank you so much for your contribution!
I updated the package in pub.dev:
https://pub.dev/packages/bitalino/versions/2.0.1
